#!/usr/bin/env python
# -*- coding: UTF-8 -*-

__author__ = "Fernando Witt"
__credits__ = ["Fernando Witt"]

__license__ = "MIT"
__version__ = "0.0.0"
__maintainer__ = "Fernando Witt"
__email__ = "ferawitt@gmail.com"

import os
import sys
import subprocess

CURRENT_DIR = os.path.abspath(os.path.dirname(__file__))
SAK_GLOBAL = os.path.abspath(os.path.join(os.environ.get('HOME'), '.sak'))

sys.path.append(SAK_GLOBAL)

def install_sak():
    if not os.path.exists(SAK_GLOBAL):
        print('No SAK installed.')

        if raw_input("Woud you like to install it? [Y/N]") in ['Y', 'y', 'yes']:
            print ('installing')

            ret_code = subprocess.call([
                'git',
                'clone',
                'https://github.com/ferwitt/sak',
                SAK_GLOBAL
                ])

            if ret_code != 0:
                print('Failed to install! Check if you have Git and internet connection')
                return ret_code
            return 0
        else:
            return -1

    print('Failed to import sak. Reason: unknown!')
    return 0

try:
    import sak
except:
    ret_code = install_sak()

    if ret_code != 0:
        sys.exit(ret_code)

    import sak
    sys.exit(sak.install())

if __name__ == "__main__":
    sak.run()
