#!/usr/bin/env python3
# -*- coding: UTF-8 -*-

__author__ = "Fernando Witt"
__credits__ = ["Fernando Witt"]

__license__ = "MIT"
__maintainer__ = "Fernando Witt"
__email__ = "ferawitt@gmail.com"

import os
import sys
import subprocess

CURRENT_DIR = os.path.abspath(os.path.dirname(__file__))
if 'SAK_GLOBAL' not in os.environ:
    SAK_GLOBAL = os.path.abspath(os.path.join(os.environ["HOME"], ".sak"))
    os.environ["SAK_GLOBAL"] = SAK_GLOBAL
else:
    SAK_GLOBAL = os.environ["SAK_GLOBAL"]

sys.path.append(SAK_GLOBAL)


def install_sak():
    if " ".join(sys.argv[1:]) == "show argcomp":
        return

    if not os.path.exists(SAK_GLOBAL):
        print("No SAK installed.")

        if input("Would you like to install it? [y/N]") in ["Y", "y", "yes"]:
            print("installing")

            ret_code = subprocess.call(
                ["git", "clone", "https://github.com/ferwitt/sak", SAK_GLOBAL]
            )

            if ret_code != 0:
                print(
                    "Failed to install! Check if you have Git and internet connection"
                )
                return ret_code
            return 0
        else:
            return -1

    print("Failed to import sak. Reason: unknown!")
    return 0


if __name__ == "__main__":
    try:
        import saklib

        saklib.run()
    except ImportError as _:
        ret_code = install_sak()

        if ret_code != 0:
            sys.exit(ret_code)

        print("Execute the sak command again to finish the installation process...")
